// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivlczsfihbbebxunymnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2bGN6c2ZpaGJiZWJ4dW55bW54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODIyMTksImV4cCI6MjA3MjY1ODIxOX0.L6plT7078dONNxuhyAFO9R5Z6N9A5OK53XPbH3O-wvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});